version: 0.2

env:
  exported-variables:
    - ARTIFACT_NAME="test-$(date +%Y-%m-%d)"
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
       - echo "Clean Stage"
       - ant -f build.xml clean
  build:
    commands:
       - echo "Build Stage"
       - ant -f build.xml
  post_build:
    commands:
       - echo "Post build phase"
artifacts:
  files:
    - '**/*'
  name: $ARTIFACT_NAME
